name: apithoitiet_retrofitflutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.3
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  retrofit_generator: ^8.0.6
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true